### PR TITLE
Add mAP Metrics and validation

### PR DESCRIPTION
**Pull request by zhiqwang**
Closes part of #59

- [x] Add mAP metric computation for COCO datasets
- [ ] Add mAP metric computation for VOC datasets
- [x] Add validation methods

### CODE REVIEW

**Comment by masahi** [comment]
Hi @zhiqwang, do you happen to have a script to evaluate yolo5 on coco 2017 dataset? I also want to evaluate torchvision faster rcnn on the same dataset. I'm working on accuracy validation of TVM fp16 quantization.

**Comment by zhiqwang** [comment]
Hi @masahi , I have the evaluate script on COCO2017, I need to clean it and expect to upload it tomorrow.

**Comment by masahi** [comment]
@zhiqwang I was able to get reasonably looking numbers by modifying the input path to the data loader in `test_vanilla_coco_evaluator` at https://github.com/zhiqwang/yolov5-rt-stack/blob/947956f3c472bd4395272e261fe6f9d46bfd8b61/test/test_engine.py#L95 to point to my downloaded coco val 2017. Was that how you did it?

Another question: I tried to use the same eval script to test torchvision fasterrcnn. But I hit an error at this line https://github.com/zhiqwang/yolov5-rt-stack/blob/f4f2e6aebec97d72ec40051aac31f217fcf01ea0/yolort/data/coco_eval.py#L201 because the label there is 86 and `contiguous_to_json_category` has only 80 elements. Why is `contiguous_to_json_category` required? If I remove `self.contiguous_to_json_category` and directly use `label[k]`, I got an accuracy number for faster rcnn, but it looks too good.

**Comment by zhiqwang** [comment]
Hi @masahi , 

Check #148 for the coco metrics evaluation CLI. Let's move the disscussion there.

> About the `self.contiguous_to_json_category`

This is because the origionall categories of COCO is discrete 91, checkout https://github.com/zhiqwang/yolov5-rt-stack/blob/f34194c/yolort/utils/builtin_meta.py for more details about the COCO categories. But ultralytics a continuous map to [1-80] to train their model.

**Pull request merged**
