### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by dkloving**

### CODE REVIEW

**Comment by zhiqwang** [comment]
Hi @dkloving , we're welcome for this contribution, if the unit-test is passed, I would like to merge this PR.

**Comment by dkloving** [comment]
Hi @zhiqwang I will be happy to create a PR once I am able to get it working, but at the moment I still am not able to produce a usable model. 

One thing that I was wondering is how to use the [SiLU fix](https://github.com/zhiqwang/yolov5-rt-stack/issues/68)? At the moment we have just copied the code that replaces SiLU units into our export functionality. It seems to work, but it's a cludge and I would prefer to use the library properly rather than copy-pasting code from it.

**Comment by zhiqwang** [comment]
HI @dkloving - you could submit your PR first and let's see how to make it work together.

**Comment by zhiqwang** [comment]
Duplicate of #79

**Pull request closed without merging**
