### PR TITLE
Replaced print() with logger #94

### LINKED ISSUE #94: Replace `print` with `logger`
## 🚀 Feature

Replace `print` statements with Python `logging` library.

### PR DESCRIPTION
**Pull request by itsabhianant**
Closes #94 

cc @zhiqwang

### CODE REVIEW

**Comment by itsabhianant** [comment]
Hi @zhiqwang ,

I have made the changes as per your instruction in the context of issue #94 .
Please feel free to let me know if any changes are needed to be made.

Best,
Abhishek

**Review by zhiqwang — APPROVED** [review]
LGTM!

**Comment by zhiqwang** [comment]
Hi @itsabhianant . Thanks for your contributions and welcome for joining `yolort` 🤗!

**Comment by itsabhianant** [comment]
> Hi @itsabhianant . Thanks for your contributions and welcome for joining `yolort` 🤗!

Thanks, @zhiqwang. I got to know about ```logging``` while working on this project so it was great working on this project 🤗🤗🤗

**Pull request merged**
